export { default as HomePage } from './HomePage'
export { default as RestaurantPage } from './RestaurantPage'
export { default as SpotPage } from './SpotPage'
export { default as RestaurantInfoPage } from './RestaurantInfoPage'
export { default as SpotInfoPage } from './SpotInfoPage'
